Update `golangci-lint` in `pre-commit`
This required fixing some new issues:

    WARN [lintersdb] The name "gas" is deprecated. The linter has been renamed to: gosec.
    cmd/validate-opslevel-annotations/main.go:186:30: Error return value is not checked (errcheck)
                            objects = append(objects, object.(client.Object))