(devena-mono) Fix Git config specific test failure
I was seeing a test failure because of how I had git configured:

    git command 'git -C /tmp/TestSecretsStubbed787089953/001 add .' failed: stderr: strongbox: 2023/11/16 10:05:27 strongbox.go:266: failed to find key id for file src/manifests/first-secret.yaml
    error: external filter 'strongbox -clean %f' failed 1
    error: external filter 'strongbox -clean %f' failed
    fatal: src/manifests/first-secret.yaml: clean filter 'strongbox' failed

Avoid this by ensuring git commands run in tests don't load and system
or user level configs via setting `GIT_CONFIG_GLOBAL`[1] to an
unreadable file.

[1] https://git-scm.com/docs/git#Documentation/git.txt-codeGITCONFIGGLOBALcode